### ISSUE TITLE
Same same playing for every condition

### ISSUE THREAD

**Issue by kcm1231** [kschuler/words-in-noise-EEG#15]
Heya, so, I just tried the newest version on my laptop, and it's playing the same sound file "action" for every trial, regardless of condition (in the AV, it's clearly a different word being said). Any idea what that's about?

Also, just to be clear, for the AV condition the task pulls the audio-only wav file, mixes it with the noise into one file, and aligns it with the video - correct? I ask because I'm going to re-normalize the word files by hand to get just the word (instead of word+silence) and I want to make sure just doing the A-only files is sufficient.   

Thanks!

**Comment by kschuler** [comment]
Check what "output.wav" is.  (listen to it).  It if it action, it probably means that sox is failing to mix new sound files. My guess would be that the subprocess is failing to execute on your computer (maybe you don't have sox installed or something).

and yes, I always pull the audio-only file for mixing.  It isn't possible to mix video sound with noise.  I just set the video to volume = 0

**Comment by kschuler** [comment]
You could find out if you have sox by open a terminal window and typing 

```
which sox
```

If you have sox, you should get an output like this:

```
/usr/local/bin/sox
```

If you don't have it... you won't get any output.

**Comment by kcm1231** [comment]
Hey Katie! Hope you had a good Thanksgiving! I was out of commission for a while with my knee surgery, but I'm trying to get this going again now. I checked, and I do have sox (When I type "which sox" I get "/usr/local/bin/sox". However, when I run the experiment in psychopy, I still get "sh: sox: command not found" and it just plays the same word (action) for every trial. Any ideas what's going on here? I'm not sure why it can't find it. 

Thanks!
