### ISSUE TITLE
Add staircase procedure before the experiment

### ISSUE THREAD

**Issue by kschuler** [kschuler/words-in-noise-EEG#5]
Staircase to find baseline of 70% (or whatever specified) and 95% (or whatever specified) signal detection.  Do them one at a time, but randomly select which one the learner does first.

Learners will start at this level in the experiment.

**Comment by kschuler** [comment]
@kcm1231 - for the baseline staircase... will they do this only for audio-only?  Or do they need a baseline for each type of stimulus? (audio, visual, environmental?)

K

**Comment by kcm1231** [comment]
We planned to get a baseline to establish easy/hard SNRs for each condition

**Comment by kschuler** [comment]
ok, great.  that is what I was thinking but wanted to double check.
