### ISSUE TITLE
Make entire experiment adaptive

### ISSUE THREAD

**Issue by kschuler** [kschuler/words-in-noise-EEG#6]
Do an interleaved QUEST staircase at 2 different SNRs (easy and hard).  Will randomly select which one to do, with at most 2 in a row of a single SNR (easy or hard).

FROM KELLY:
While I was meeting with Peter, he wanted to know if there was a way to make the entire experiment adaptive. Meaning that, at the beginning of the task the subject would do a mini staircase procedure to establish initial Hard and Easy SNRs, but during the actual task the program would continue to check response accuracy and increase/decrease SNRs as needed to make sure the subjects stay at the same ave percent correct. This would be ideal because it would account for any learning that goes on during the task.

**Comment by kschuler** [comment]
@kcm1231 - I am assuming you actually need 6 staircases.  (One for each condition at each SNR - easy and hard).  Is this right?  (Because if there were only two staircases - one for easy and one for hard - the staircase is constantly adjusted, doing something well for visual would also adjust the staircase for audio-only).

Can you let me know if this is correct?  How I structure the experiment depends on the answer to this.

K

**Comment by kcm1231** [comment]
Yep! 6 staircases is right. Will that work?

**Comment by kschuler** [comment]
Yep!  6 is just as easy as 2. Just wanted to make sure I was interpreting it correctly. :)

**Comment by kschuler** [comment]
@kcm1231 Hey kelly,

I'm almost finished making all of the changes, but I have two questions that effect how I structure the experiment.

(1) If you have a completely adaptive experiment, is there still a need for the initial baseline staircase?

(2) what kind of staircase do you guys want?  It is fairly easy for me to implement either a traditional simple adaptive stair (n-up, n-down)... but doesn't allow you to select 70% and 95% as discrimination criteria.  Because of this I was assuming QUEST, because it allows you to select a threshold value, but it also kind of requires that you know (somewhat) the underlying psych. function.  Do you guys have a preference between the two?

There is a great response on the psychopy group about exactly the issue in (2) with some useful citations for your reference: http://discourse.psychopy.org/t/setting-performance-levels-at-65-and-85-using-adaptive-staircase/914

**Comment by kcm1231** [comment]
Hey! That's great!!

1) So, even if the whole experiment is adaptive, we want to know each participant's  70/95% SNRs before the actual experiment starts, that way we can start them there and just make sure those thresholds are maintained throughout the experiment.

2) Yes, we definitely want to set specific thresholds, so it sounds like we'll have to use QUEST.  If that means we need to have to do some piloting to get an estimate of the psychometric function, that's something we can do. 

Does that answer everything?

**Comment by kschuler** [comment]
cool!  Yep, that's great.  thanks :)
